### PR TITLE
Add CoffeeScript implementation

### PR DESCRIPTION
**Pull request by afnizarnur**

### CODE REVIEW

**Comment by afnizarnur** [comment]
@mburst Please check this PR :) Thanks!

**Comment by odahcam** [comment]
up

**Comment by odahcam** [comment]
up

**Comment by odahcam** [comment]
up

**Comment by odahcam** [comment]
up

**Comment by mburst** [comment]
Somehow missed this. Thanks for the bump. Verified it works

**Comment by mburst** [comment]
Somehow missed this. Thanks for the bump. Verified it works

**Comment by odahcam** [comment]
You're welcome.

**Pull request merged**
